//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSSolution.Models.OnlineModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bill()
        {
            this.BillItems = new HashSet<BillItem>();
            this.BillReturnItems = new HashSet<BillReturnItem>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public double SubTotal { get; set; }
        public double Discount { get; set; }
        public double ReturnAmount { get; set; }
        public double NetTotal { get; set; }
        public double CashAmount { get; set; }
        public double ChequeAmount { get; set; }
        public double PaidAmount { get; set; }
        public int BilledBy { get; set; }
        public int ShownBy { get; set; }
        public string Status { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillItem> BillItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillReturnItem> BillReturnItems { get; set; }
    }
}
