//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSSolution.Models.OnlineModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cheque
    {
        public int Id { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string Number { get; set; }
        public string Bank { get; set; }
        public string Branch { get; set; }
        public double Amount { get; set; }
        public System.DateTime Date { get; set; }
        public int CustomerId { get; set; }
        public string Description { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public string Status { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
