//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSSolution.Models.OnlineModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineDatabaseEntities : DbContext
    {
        public OnlineDatabaseEntities()
            : base("name=OnlineDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<BillItem> BillItems { get; set; }
        public virtual DbSet<BillReturnItem> BillReturnItems { get; set; }
        public virtual DbSet<Cheque> Cheques { get; set; }
        public virtual DbSet<Collection> Collections { get; set; }
        public virtual DbSet<Credit> Credits { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Expense> Expenses { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Normal> Normals { get; set; }
        public virtual DbSet<NormalItem> NormalItems { get; set; }
        public virtual DbSet<NormalReturnItem> NormalReturnItems { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PaymentBill> PaymentBills { get; set; }
        public virtual DbSet<PaymentBillItem> PaymentBillItems { get; set; }
        public virtual DbSet<PaymentBillReturnItem> PaymentBillReturnItems { get; set; }
        public virtual DbSet<Purchase> Purchases { get; set; }
        public virtual DbSet<ReturnBill> ReturnBills { get; set; }
        public virtual DbSet<ReturnBillItem> ReturnBillItems { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
