//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentBillReturnItem
    {
        public int Id { get; set; }
        public int PaymentBillId { get; set; }
        public int QTY { get; set; }
        public string ItemName { get; set; }
        public double UnitPrice { get; set; }
        public double SubTotal { get; set; }
        public double Discount { get; set; }
        public double NetTotal { get; set; }
    
        public virtual PaymentBill PaymentBill { get; set; }
    }
}
